/obj/machinery/power/geothermal_turbine
	//icon = todo
	//icon_state = todo
	density = TRUE
	resistance_flags = FIRE_PROOF
	can_atmos_pass = ATMOS_PASS_DENSITY
	processing_flags = START_PROCESSING_MANUALLY
	///The gas mix going through the turbine
	var/datum/gas_mixture/turbine_gasmix
	///The cooling gas mix
	var/datum/gas_mixture/cooling_gasmix
	///Amount of mechanical stress
	var/stress = 0
	///Maximum stress
	var/max_stress = 100
	/// current input valve setting in liters per second
	var/input_valve_lps = 0
	///rate of gaz flow, function of (input_valve * (turbine_gasmix pressure - ouptut gasmix pressure)
	var/flow_rate = 0
	///current internal Filter Setting (0: filter not deployed, 100: filter fully deployed)
	var/filter = 0
	///current rpm
	var/rpm = 0
	///current condenser efficiency setting (0: minimum efficiency, 100: maximum efficiency)
	var/condenser_efficiency

/obj/machinery/power/geothermal_turbine/Initialize(mapload, gas_theoretical_volume)
	. = ..()

	turbine_gasmix = new
	turbine_gasmix.volume = gas_theoretical_volume
	cooling_gasmix = new
	cooling_gasmix.volume = gas_theoretical_volume

/datum/gas/water_vapor/mineral_impurities
	id = GAS_WATER_VAPOR_MINERAL_IMPURITIES
	name = "Water Vapor with Mineral Impurities"
	desc = "Water vapor containing trace minerals. Slightly more conductive and leaves residue on surfaces."
	primary_color = "#a0b0c0"
	specific_heat = 38 // slightly lower due to impurities
	base_value = 0.6 // slightly more valuable
	moles_visible = MOLES_GAS_VISIBLE
	purchaseable = FALSE

/obj/machinery/power/geothermal_turbine/process()
	if(linked_input_pipe && linked_input_pipe.air_contents)
		var/datum/gas_mixture/input_mix = linked_input_pipe.air_contents

		var/total_moles = input_mix.total_moles()
		if(total_moles > 0)
			var/moles_to_pull = input_valve_lps
			var/fraction = min(moles_to_pull / total_moles, 1)

			var/datum/gas_mixture/pulled_mix = input_mix.remove_ratio(fraction)
			turbine_gasmix.merge(pulled_mix)

	if(turbine_gasmix)
		for(var/datum/gas/current_gas in turbine_gasmix.gases)
			var/moles_of_current_gas = turbine_gasmix.gases[current_gas]

			// Skip pure water vapor
			if(istype(current_gas, /datum/gas/water_vapor) && !istype(current_gas, /datum/gas/water_vapor/mineral_impurities))
				continue

			// Special case: mineral impurities
			if(istype(current_gas, /datum/gas/water_vapor/mineral_impurities))
				var/filter_fraction = clamp(1 - (filter / 100), 0, 1)
				var/reduced_moles = moles_of_current_gas * filter_fraction
				turbine_gasmix.gases[current_gas] = reduced_moles
				stress += round(reduced_moles * 0.1)
			else
				stress += round(moles_of_current_gas * 0.1)

	var/input_pressure = turbine_gasmix?.return_pressure() || 0
	var/output_pressure = linked_output_pipe?.air_contents?.return_pressure() || 0

	var/effective_output_pressure = output_pressure * (1 - condenser_efficiency / 100)
	flow_rate = input_valve_lps * max(input_pressure - effective_output_pressure, 0)
	rpm = flow_rate * (condenser_efficiency / 100)

	if(cooling_gasmix)
		// Coolant flow reduces turbine stress
		var/stress_reduction = coolant_flow * 0.05
		stress = max(stress - stress_reduction, 0)

		// Heat generated by turbine operation
		var/heat_generated = (condenser_efficiency * 0.1) + (coolant_flow * 0.2)

		// Calculate total heat capacity of coolant mixture
		var/total_heat_capacity = 0
		for(var/datum/gas/current_coolant_gas in cooling_gasmix.gases)
			var/moles_of_coolant_gas = cooling_gasmix.gases[current_coolant_gas]
			total_heat_capacity += moles_of_coolant_gas * current_coolant_gas.specific_heat

		// Apply temperature increase based on heat capacity
		if(total_heat_capacity > 0)
			var/temperature_increase = heat_generated / total_heat_capacity
			cooling_gasmix.temperature += temperature_increase

		// Condenser effect on exhaust gas
		if(turbine_gasmix)
			var/exhaust_cooling_factor = condenser_efficiency / 100
			var/exhaust_temperature_drop = turbine_gasmix.temperature * exhaust_cooling_factor * 0.2
			turbine_gasmix.temperature = max(turbine_gasmix.temperature - exhaust_temperature_drop, 0)

	if(linked_output_pipe && linked_output_pipe.air_contents && turbine_gasmix)
		linked_output_pipe.air_contents.merge(turbine_gasmix)
		turbine_gasmix = new /datum/gas_mixture() // clear chamber for next cycle

	if(stress > max_stress)
		// catastrophic failure
		qdel(src)
