//ATMOS MIX IDS
#define THALASSOSTATION_DEFAULT_ATMOS "THALASSOSTATION_DEFAULT_ATMOS"
#define THALASSOSTATION_BATHYPELAGIC_ATMOS "THALASSOSTATION_BATHYPELAGIC_ATMOS"

/// The minimum temperature of Thalassostation
#define THALASSOSTATION_MIN_TEMPERATURE 293
/// The maximum temperature of Thalassostation
#define THALASSOSTATION_MAX_TEMPERATURE 310
